/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreatePruductArgs } from "./CreatePruductArgs";
import { UpdatePruductArgs } from "./UpdatePruductArgs";
import { DeletePruductArgs } from "./DeletePruductArgs";
import { PruductFindManyArgs } from "./PruductFindManyArgs";
import { PruductFindUniqueArgs } from "./PruductFindUniqueArgs";
import { Pruduct } from "./Pruduct";
import { User } from "../../user/base/User";
import { PruductService } from "../pruduct.service";

@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Pruduct)
export class PruductResolverBase {
  constructor(
    protected readonly service: PruductService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Pruduct",
    action: "read",
    possession: "any",
  })
  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Pruduct",
    action: "read",
    possession: "any",
  })
  async _pruductsMeta(
    @graphql.Args() args: PruductFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Pruduct])
  @nestAccessControl.UseRoles({
    resource: "Pruduct",
    action: "read",
    possession: "any",
  })
  @nestAccessControl.UseRoles({
    resource: "Pruduct",
    action: "read",
    possession: "any",
  })
  async pruducts(
    @graphql.Args() args: PruductFindManyArgs
  ): Promise<Pruduct[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Pruduct, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Pruduct",
    action: "read",
    possession: "own",
  })
  @nestAccessControl.UseRoles({
    resource: "Pruduct",
    action: "read",
    possession: "own",
  })
  async pruduct(
    @graphql.Args() args: PruductFindUniqueArgs
  ): Promise<Pruduct | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Pruduct)
  @nestAccessControl.UseRoles({
    resource: "Pruduct",
    action: "create",
    possession: "any",
  })
  @nestAccessControl.UseRoles({
    resource: "Pruduct",
    action: "create",
    possession: "any",
  })
  async createPruduct(
    @graphql.Args() args: CreatePruductArgs
  ): Promise<Pruduct> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        test: args.data.test
          ? {
              connect: args.data.test,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Pruduct)
  @nestAccessControl.UseRoles({
    resource: "Pruduct",
    action: "update",
    possession: "any",
  })
  @nestAccessControl.UseRoles({
    resource: "Pruduct",
    action: "update",
    possession: "any",
  })
  async updatePruduct(
    @graphql.Args() args: UpdatePruductArgs
  ): Promise<Pruduct | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          test: args.data.test
            ? {
                connect: args.data.test,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Pruduct)
  @nestAccessControl.UseRoles({
    resource: "Pruduct",
    action: "delete",
    possession: "any",
  })
  @nestAccessControl.UseRoles({
    resource: "Pruduct",
    action: "delete",
    possession: "any",
  })
  async deletePruduct(
    @graphql.Args() args: DeletePruductArgs
  ): Promise<Pruduct | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async test(@graphql.Parent() parent: Pruduct): Promise<User | null> {
    const result = await this.service.getTest(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
